#!/bin/sh

if [ -f /etc/clearos/qos.conf ]; then
    logger -p local6.notice -t installer "app-qos-core - disabling qos"
    sed -i -e 's/QOS_ENABLE="on"/QOS_ENABLE="off"/g' /etc/clearos/qos.conf
    systemctl restart firewall
    systemctl restart firewall6
fi
